### ISSUE TITLE
Can't import ConnectHandler (MacOSX & CentOS)

### ISSUE THREAD

**Issue by punkrokk** [ktbyers/netmiko#571]
Hi, 

Using a virtualenv, I am unable to run the following: 

#!/usr/bin/env python3

import argparse
import logging
import sys
import os

from netmiko import ConnectHandler

It works fine in the console with the python 3.6.2 interpreter (same as my virtual environment). 
I see that is says py3.5 is what's supported, but I have the same issue with 2.7. 

I get this: 

` Traceback (most recent call last):
  File "/Users/punkrokk/repos/irflow-integrations/integrations/netmiko/netmiko.py", line 8, in <module>
    from netmiko import ConnectHandler
  File "/Users/punkrokk/repos/irflow-integrations/integrations/netmiko/netmiko.py", line 8, in <module>
    from netmiko import ConnectHandler
ImportError: cannot import name 'ConnectHandler'

Process finished with exit code 1 `

Any thoughts on troubleshooting?

**Comment by ktbyers** [comment]
@punkrokk It looks like you have created a file name `netmiko.py` and it is trying to import from that and not from the netmiko library:

```
/Users/punkrokk/repos/irflow-integrations/integrations/netmiko/netmiko.py
```

You need to rename this file and remove any .pyc files that were created.

**Comment by punkrokk** [comment]
that was it! thanks @ktbyers
